[tool.ruff]
select = ["E", "F", "I", "N", "W", "U", "COM", "RUF", "PLC", "PLE", "PLW"]
# Ensure suggested fixes are compatible with our minimum supported version
target-version = "py38"
ignore = [
    "PLW2901", # `for` loop variable `value` overwritten by assignment target
    "RUF012",  # Mutable class attributes should be annotated with `typing.ClassVar` (cannot be fixed due to bug)
]
exclude = [
    ".git",
    ".idea",
    ".run",
    ".pytype/",
    ".venv",
    "3rdparty",
    "venv",
]
line-length = 120

[tool.black]
line-length = 120
target-version = ['py38']
# 'extend-exclude' excludes files or directories in addition to the defaults
# Currently reformatting pycheribuild/ results in lots of weird formatting, so
# let's restrict this to the other files for now.
extend-exclude = '''3rdparty|\.pytype|pycheribuild'''
preview = true
required-version = '23'

[tool.ruff.isort]
relative-imports-order = "closest-to-furthest"
known-local-folder = ["pycheribuild"]
